alias vim='nvim'
alias vi='nvim .'
alias rm='echo "Use \rm instead"'
alias bat='batcat '
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias neofetch='neofetch --ascii ~/Pictures/chibi-spiderman.txt'
